config:
  partrtial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
dbt_tranformation_handson:
  outputs:
    prod:
      dbname: my_new_database
      host: 10.168.158.18
      pass: mypassword
      port: 3030
      schema: public
      threads: 8
      type: postgres
      user: myusername
  target: prod
