version: 2
sources:
  - name: raw_table
    database: my_new_database
    schema: __destination_database_
    tables:
      - name: _airbyte_raw_products
      - name: _airbyte_raw_table_two

models:
  - name: emp_products
    columns:
      - name: product_id
      - name: product_name
      - name: price
      - name: updated_at
  - name: emp_table_two
    columns:
      - name: id
      - name: name
      - name: updated_at
