version: 2
sources:
  - name: raw_table
    database: my_new_database
    schema: __destination_database
    tables:
      - name: _airbyte_raw_company

models:
  - name: emp_company
    columns:
      - name: id
      - name: age
      - name: name
      - name: salary

