version: 2
sources:
  - name: raw_company_table
    database: my_new_database
    schema: __destination_database
    description: A replica of the mysql database.
    tables:
      - name: _airbyte_raw_company
models:
  - name: company_table
    columns:
      - name: id
      - name: age
      - name: name
      - name: salary

