version: 2
sources:
  - name: raw_table
    database: my_new_database
    schema: __destination_database
    tables:
      - name: _airbyte_raw_company
      - name: _airbyte_raw_department
models:
  - name: emp_company
    columns:
      - name: id
      - name: age
      - name: name
      - name: salary
  - name: emp_department
    columns:
      - name: id
      - name: dept
      - name: emp_id

