version: 2
sources:
  - name: new_database
    description: A replica of the mysql database.
    tables:
      - name: company
models:
  - name: company
    columns:
      - name: id
      - name: age
      - name: name
      - name: salary

