version: 2
config:
  parrtial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
dbt_transformation_handson:
  outputs:
    dev:
      dbname: my_new_database
      host: 10.168.158.18
      pass: mypassword
      port: 3030
      schema: __destination_database_
      threads: 8
      type: postgres
      user: myusername
  target: dev
