
version: 2
sources:
  - name: my_new_database
    description: A replica of the mysql database.
    tables:
      - name: company
        columns:
          - name: EMP_ID
            description: Primary key of the table
            tests:
              - unique
              - not_null

models:

  - name:company
    config:
      materialized: view
    columns:
      - name: EMP_ID
	description: Primary key of the table
        tests:
          - unique
          - not_null
