version: 2
sources:
- name: __destination_database_
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_company
  - name: _airbyte_raw_department
  - name: _airbyte_raw_table_two
